# --- Configuration locale / Docker ---
db.urlDev=jdbc:mysql://localhost:3306/companydb?useSSL=false&serverTimezone=UTC
db.username=user
db.password=passer123@

# --- Configuration production via variables d'environnement ---
db.urlProd=${env.DB_URL_PROD}
db.user=${env.COMPANY_DB_USER}
db.pwd=${env.COMPANY_DB_PWD}