services:
  test:mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
  
phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD:root
      PMA_HOST: mysql
      PMA_USER:user
      PMA_PASSWORD:passer@123
    depends_on:
      - mysql
    restart: unless-stopped

  volumes:
    mysql_company_data:
     driver:local
