version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: container-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: companydb
      MYSQL_USER: user
      MYSQL_PASSWORD: passer123@
    ports:
      - "3306:3306"
    volumes:
      - mysql_company_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "user", "--password=passer123@"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "81:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: passer123@
      PMA_PORT: 3306
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_company_data:
    driver: local